INFO 2023-08-31 15:28:36,716 autoreload 3900 11356 Watching for file changes with StatReloader
INFO 2023-08-31 15:28:41,449 views 3900 16544 index page log
INFO 2023-08-31 15:28:41,518 basehttp 3900 16544 "GET / HTTP/1.1" 200 40
WARNING 2023-08-31 15:28:41,694 log 3900 16544 Not Found: /favicon.ico
WARNING 2023-08-31 15:28:41,704 basehttp 3900 16544 "GET /favicon.ico HTTP/1.1" 404 2441
INFO 2023-08-31 16:13:15,135 autoreload 7396 5896 Watching for file changes with StatReloader
INFO 2023-08-31 16:13:49,100 autoreload 20744 9472 Watching for file changes with StatReloader
INFO 2023-08-31 16:15:29,293 autoreload 20744 9472 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\seminar_1\views.py changed, reloading.
INFO 2023-08-31 16:15:29,900 autoreload 14900 11844 Watching for file changes with StatReloader
INFO 2023-08-31 16:15:34,351 autoreload 14644 19388 Watching for file changes with StatReloader
INFO 2023-08-31 16:15:37,194 views 14644 1324 index page log
INFO 2023-08-31 16:15:37,195 basehttp 14644 1324 "GET / HTTP/1.1" 200 40
WARNING 2023-08-31 16:15:50,733 log 14644 1324 Not Found: /cube
WARNING 2023-08-31 16:15:50,734 basehttp 14644 1324 "GET /cube HTTP/1.1" 404 2636
INFO 2023-08-31 16:17:25,507 autoreload 14644 19388 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\seminar_1\urls.py changed, reloading.
INFO 2023-08-31 16:17:26,075 autoreload 20412 11912 Watching for file changes with StatReloader
INFO 2023-08-31 16:17:30,443 autoreload 15872 12036 Watching for file changes with StatReloader
WARNING 2023-08-31 16:17:35,163 log 15872 4580 Not Found: /cube
WARNING 2023-08-31 16:17:35,164 basehttp 15872 4580 "GET /cube HTTP/1.1" 404 2636
WARNING 2023-08-31 16:17:51,178 log 15872 4580 Not Found: /cube
WARNING 2023-08-31 16:17:51,179 basehttp 15872 4580 "GET /cube HTTP/1.1" 404 2636
WARNING 2023-08-31 16:19:58,041 log 15872 4580 Not Found: /seminar_1/cube
WARNING 2023-08-31 16:19:58,041 basehttp 15872 4580 "GET /seminar_1/cube HTTP/1.1" 404 3112
INFO 2023-08-31 16:20:12,670 autoreload 15872 12036 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\seminar_1\urls.py changed, reloading.
INFO 2023-08-31 16:20:13,330 autoreload 16748 12388 Watching for file changes with StatReloader
INFO 2023-08-31 16:20:14,771 basehttp 16748 18688 "GET /seminar_1/cube HTTP/1.1" 301 0
INFO 2023-08-31 16:20:14,774 basehttp 16748 9468 "GET /seminar_1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 16:20:16,049 basehttp 16748 9468 "GET /seminar_1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 16:20:17,005 basehttp 16748 9468 "GET /seminar_1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 16:20:17,951 basehttp 16748 9468 "GET /seminar_1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 16:20:18,874 basehttp 16748 9468 "GET /seminar_1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 16:20:19,748 basehttp 16748 9468 "GET /seminar_1/cube/ HTTP/1.1" 200 1
INFO 2023-08-31 16:20:31,401 basehttp 16748 9468 "GET /seminar_1/rand_num HTTP/1.1" 301 0
INFO 2023-08-31 16:20:31,413 basehttp 16748 12344 "GET /seminar_1/rand_num/ HTTP/1.1" 200 2
INFO 2023-08-31 16:20:33,488 basehttp 16748 12344 "GET /seminar_1/rand_num/ HTTP/1.1" 200 2
INFO 2023-08-31 16:20:33,916 basehttp 16748 12344 "GET /seminar_1/rand_num/ HTTP/1.1" 200 2
INFO 2023-08-31 16:20:34,289 basehttp 16748 12344 "GET /seminar_1/rand_num/ HTTP/1.1" 200 2
INFO 2023-08-31 16:20:34,653 basehttp 16748 12344 "GET /seminar_1/rand_num/ HTTP/1.1" 200 2
INFO 2023-08-31 16:20:35,063 basehttp 16748 12344 "GET /seminar_1/rand_num/ HTTP/1.1" 200 2
INFO 2023-09-01 16:08:48,503 autoreload 2948 17892 Watching for file changes with StatReloader
INFO 2023-09-01 16:08:54,933 views 2948 4944 index page log
INFO 2023-09-01 16:08:54,978 basehttp 2948 4944 "GET / HTTP/1.1" 200 40
WARNING 2023-09-01 16:08:55,170 log 2948 4944 Not Found: /favicon.ico
WARNING 2023-09-01 16:08:55,194 basehttp 2948 4944 "GET /favicon.ico HTTP/1.1" 404 2762
INFO 2023-09-01 16:09:10,493 basehttp 2948 21100 "GET /hw_1/about HTTP/1.1" 301 0
INFO 2023-09-01 16:09:10,498 basehttp 2948 20828 "GET /hw_1/about/ HTTP/1.1" 200 31
WARNING 2023-09-01 16:09:18,462 log 2948 20828 Not Found: /hw_1/
WARNING 2023-09-01 16:09:18,463 basehttp 2948 20828 "GET /hw_1/ HTTP/1.1" 404 2983
INFO 2023-09-07 15:26:35,882 autoreload 7268 17496 Watching for file changes with StatReloader
INFO 2023-09-07 15:27:18,778 autoreload 7268 17496 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\lecture_3\urls.py changed, reloading.
INFO 2023-09-07 15:27:23,162 autoreload 15892 7212 Watching for file changes with StatReloader
INFO 2023-09-07 15:29:39,002 autoreload 23488 24396 Watching for file changes with StatReloader
INFO 2023-09-07 15:31:01,495 autoreload 12004 18212 Watching for file changes with StatReloader
INFO 2023-09-07 15:31:06,356 views 12004 4560 index page log
INFO 2023-09-07 15:31:06,398 basehttp 12004 4560 "GET / HTTP/1.1" 200 40
WARNING 2023-09-07 15:31:06,680 log 12004 4560 Not Found: /favicon.ico
WARNING 2023-09-07 15:31:06,689 basehttp 12004 4560 "GET /favicon.ico HTTP/1.1" 404 2872
INFO 2023-09-07 15:31:36,769 basehttp 12004 5992 "GET /lecture_3 HTTP/1.1" 301 0
INFO 2023-09-07 15:31:36,794 basehttp 12004 15088 "GET /lecture_3/ HTTP/1.1" 200 151
INFO 2023-09-09 13:49:28,822 autoreload 21968 9680 Watching for file changes with StatReloader
WARNING 2023-09-09 13:49:34,442 log 21968 13868 Not Found: /favicon.ico
WARNING 2023-09-09 13:49:34,498 basehttp 21968 13868 "GET /favicon.ico HTTP/1.1" 404 2872
INFO 2023-09-09 13:49:43,620 basehttp 21968 23876 "GET /lecture_3/if HTTP/1.1" 301 0
INFO 2023-09-09 13:49:43,634 basehttp 21968 21908 "GET /lecture_3/if/ HTTP/1.1" 200 326
INFO 2023-09-09 13:50:55,214 basehttp 21968 14744 "GET /lecture_3/if/ HTTP/1.1" 200 330
INFO 2023-09-09 13:51:28,476 basehttp 21968 14744 "GET /lecture_3/if/ HTTP/1.1" 200 339
INFO 2023-09-10 15:23:34,579 autoreload 15600 5964 Watching for file changes with StatReloader
INFO 2023-09-10 15:25:49,204 autoreload 15600 5964 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_3\views.py changed, reloading.
INFO 2023-09-10 15:25:49,872 autoreload 6168 13204 Watching for file changes with StatReloader
INFO 2023-09-10 15:25:56,337 views 6168 14748 index page log
INFO 2023-09-10 15:25:56,342 basehttp 6168 14748 "GET / HTTP/1.1" 200 40
WARNING 2023-09-10 15:25:56,461 log 6168 14748 Not Found: /favicon.ico
WARNING 2023-09-10 15:25:56,468 basehttp 6168 14748 "GET /favicon.ico HTTP/1.1" 404 3087
WARNING 2023-09-10 15:26:20,566 log 6168 18264 Not Found: /lecture_4
WARNING 2023-09-10 15:26:20,567 basehttp 6168 18264 "GET /lecture_4 HTTP/1.1" 404 3081
WARNING 2023-09-10 15:26:45,310 log 6168 18264 Not Found: /lecture_4/
WARNING 2023-09-10 15:26:45,311 basehttp 6168 18264 "GET /lecture_4/ HTTP/1.1" 404 3346
INFO 2023-09-10 15:26:58,714 basehttp 6168 18264 "GET /lecture_4/forms HTTP/1.1" 301 0
INFO 2023-09-10 15:26:58,753 basehttp 6168 18388 "GET /lecture_4/forms/ HTTP/1.1" 200 1422
INFO 2023-09-10 15:34:20,031 autoreload 6168 13204 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\lecture_4\forms.py changed, reloading.
INFO 2023-09-10 15:34:20,817 autoreload 9596 5560 Watching for file changes with StatReloader
INFO 2023-09-10 15:37:12,241 autoreload 9596 5560 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\lecture_4\forms.py changed, reloading.
INFO 2023-09-10 15:37:12,973 autoreload 4296 3172 Watching for file changes with StatReloader
INFO 2023-09-10 15:40:54,691 autoreload 4296 3172 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\lecture_4\views.py changed, reloading.
INFO 2023-09-10 15:40:55,363 autoreload 15716 14216 Watching for file changes with StatReloader
INFO 2023-09-10 15:40:59,719 basehttp 15716 16808 "GET /lecture_4/forms/ HTTP/1.1" 200 2043
INFO 2023-09-10 15:44:41,815 autoreload 15716 14216 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\lecture_4\forms.py changed, reloading.
INFO 2023-09-10 15:44:42,562 autoreload 19716 6168 Watching for file changes with StatReloader
INFO 2023-09-10 15:44:47,359 basehttp 19716 13840 "GET /lecture_4/forms/ HTTP/1.1" 200 2043
INFO 2023-09-10 15:53:23,969 autoreload 19716 6168 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\lecture_4\forms.py changed, reloading.
INFO 2023-09-10 15:53:24,895 autoreload 18472 20364 Watching for file changes with StatReloader
INFO 2023-09-10 16:00:15,840 autoreload 18472 20364 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\lecture_4\models.py changed, reloading.
INFO 2023-09-10 16:00:16,729 autoreload 13840 12532 Watching for file changes with StatReloader
INFO 2023-09-10 16:11:00,118 autoreload 13816 19936 Watching for file changes with StatReloader
INFO 2023-09-10 16:11:12,803 basehttp 13816 13328 "GET /lecture_4/user HTTP/1.1" 301 0
INFO 2023-09-10 16:11:12,831 basehttp 13816 8584 "GET /lecture_4/user/ HTTP/1.1" 200 897
INFO 2023-09-10 16:11:26,303 basehttp 13816 8584 "POST /lecture_4/user/ HTTP/1.1" 200 1038
INFO 2023-09-10 16:12:27,107 basehttp 13816 8584 "POST /lecture_4/user/ HTTP/1.1" 200 958
INFO 2023-09-10 16:18:55,384 autoreload 13816 19936 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\myproject\settings.py changed, reloading.
INFO 2023-09-10 16:18:56,239 autoreload 9028 1064 Watching for file changes with StatReloader
INFO 2023-09-10 16:21:54,557 autoreload 9028 1064 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\lecture_4\views.py changed, reloading.
INFO 2023-09-10 16:21:55,345 autoreload 16488 17892 Watching for file changes with StatReloader
INFO 2023-09-10 16:24:35,617 autoreload 16488 17892 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\lecture_4\views.py changed, reloading.
INFO 2023-09-10 16:24:36,446 autoreload 2400 3240 Watching for file changes with StatReloader
INFO 2023-09-10 16:26:44,082 autoreload 2400 3240 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\lecture_4\views.py changed, reloading.
INFO 2023-09-10 16:26:44,881 autoreload 1904 9800 Watching for file changes with StatReloader
INFO 2023-09-10 16:27:50,416 autoreload 1904 9800 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\lecture_4\urls.py changed, reloading.
INFO 2023-09-10 16:27:51,207 autoreload 12020 18108 Watching for file changes with StatReloader
INFO 2023-09-13 15:24:43,311 autoreload 19004 4180 Watching for file changes with StatReloader
INFO 2023-09-13 15:24:49,247 views 19004 13256 index page log
INFO 2023-09-13 15:24:49,266 basehttp 19004 13256 "GET / HTTP/1.1" 200 40
WARNING 2023-09-13 15:24:49,374 log 19004 13256 Not Found: /favicon.ico
WARNING 2023-09-13 15:24:49,384 basehttp 19004 13256 "GET /favicon.ico HTTP/1.1" 404 3087
WARNING 2023-09-13 15:25:06,208 log 19004 2176 Not Found: /hw_4/client/add
WARNING 2023-09-13 15:25:06,209 basehttp 19004 2176 "GET /hw_4/client/add HTTP/1.1" 404 3099
INFO 2023-09-13 15:25:43,717 autoreload 19004 4180 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\myproject\urls.py changed, reloading.
INFO 2023-09-13 15:25:44,502 autoreload 14732 10492 Watching for file changes with StatReloader
INFO 2023-09-13 15:25:48,293 basehttp 14732 13816 "GET /hw_4/client/add HTTP/1.1" 301 0
ERROR 2023-09-13 15:25:48,345 log 14732 18660 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw_3/client_form.html
ERROR 2023-09-13 15:25:48,351 basehttp 14732 18660 "GET /hw_4/client/add/ HTTP/1.1" 500 87117
ERROR 2023-09-13 15:31:04,996 log 14732 11932 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw_3/client_form.html
ERROR 2023-09-13 15:31:05,000 basehttp 14732 11932 "GET /hw_4/client/add/ HTTP/1.1" 500 87117
INFO 2023-09-13 15:34:16,434 autoreload 14732 10492 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\urls.py changed, reloading.
INFO 2023-09-13 15:34:17,378 autoreload 17304 18820 Watching for file changes with StatReloader
ERROR 2023-09-13 15:34:17,679 log 17304 19140 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw_3/client_form.html
ERROR 2023-09-13 15:34:17,682 basehttp 17304 19140 "GET /hw_4/client/add/ HTTP/1.1" 500 87117
INFO 2023-09-13 15:34:57,013 autoreload 17304 18820 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\views.py changed, reloading.
INFO 2023-09-13 15:34:57,706 autoreload 3928 8584 Watching for file changes with StatReloader
INFO 2023-09-13 15:34:58,321 basehttp 3928 12512 "GET /hw_4/client/add/ HTTP/1.1" 200 1069
ERROR 2023-09-13 15:35:15,035 log 3928 12512 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'hw_3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py", line 17, in get_absolute_url
    return reverse('hw_3:client_detail', kwargs={'pk': self.pk})
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'hw_3' is not a registered namespace
ERROR 2023-09-13 15:35:15,040 basehttp 3928 12512 "POST /hw_4/client/add/ HTTP/1.1" 500 114726
INFO 2023-09-13 15:36:36,266 autoreload 3928 8584 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py changed, reloading.
INFO 2023-09-13 15:36:37,120 autoreload 14368 2160 Watching for file changes with StatReloader
ERROR 2023-09-13 15:36:40,833 log 14368 15344 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'hw_4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py", line 17, in get_absolute_url
    return reverse('hw_4:client_detail', kwargs={'pk': self.pk})
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'hw_4' is not a registered namespace
ERROR 2023-09-13 15:36:40,837 basehttp 14368 15344 "POST /hw_4/client/add/ HTTP/1.1" 500 114726
INFO 2023-09-13 15:37:20,096 autoreload 14368 2160 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py changed, reloading.
INFO 2023-09-13 15:37:20,981 autoreload 3616 19140 Watching for file changes with StatReloader
ERROR 2023-09-13 15:37:22,838 log 3616 15112 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'hw_4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py", line 17, in get_absolute_url
    return reverse('hw_4:client_page', kwargs={'pk': self.pk})
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'hw_4' is not a registered namespace
ERROR 2023-09-13 15:37:22,842 basehttp 3616 15112 "POST /hw_4/client/add/ HTTP/1.1" 500 114714
ERROR 2023-09-13 15:37:26,920 log 3616 15112 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'hw_4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py", line 17, in get_absolute_url
    return reverse('hw_4:client_page', kwargs={'pk': self.pk})
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'hw_4' is not a registered namespace
ERROR 2023-09-13 15:37:26,924 basehttp 3616 15112 "POST /hw_4/client/add/ HTTP/1.1" 500 114714
ERROR 2023-09-13 15:38:25,858 log 3616 15112 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'hw_4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py", line 17, in get_absolute_url
    return reverse('hw_4:client_page', kwargs={'pk': self.pk})
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'hw_4' is not a registered namespace
ERROR 2023-09-13 15:38:25,866 basehttp 3616 15112 "POST /hw_4/client/add/ HTTP/1.1" 500 114714
INFO 2023-09-13 15:45:54,772 basehttp 3616 18924 "GET /hw_4/client/4 HTTP/1.1" 301 0
INFO 2023-09-13 15:45:54,793 basehttp 3616 18724 "GET /hw_4/client/4/ HTTP/1.1" 200 282
INFO 2023-09-13 15:48:55,082 autoreload 3616 19140 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\urls.py changed, reloading.
INFO 2023-09-13 15:48:56,304 autoreload 5600 2180 Watching for file changes with StatReloader
ERROR 2023-09-13 15:49:26,120 log 5600 18572 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 135, in form_valid
    self.object = form.save()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1833, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\backends\base\operations.py", line 213, in fetch_returned_insert_columns
    return cursor.fetchone()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\utils.py", line 97, in inner
    with self:
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
django.db.utils.OperationalError: database is locked
ERROR 2023-09-13 15:49:26,130 basehttp 5600 18572 "POST /hw_4/client/add/ HTTP/1.1" 500 153845
INFO 2023-09-13 15:49:46,427 autoreload 2612 1384 Watching for file changes with StatReloader
INFO 2023-09-13 15:49:49,225 basehttp 2612 8480 "GET /hw_4/client/add/ HTTP/1.1" 200 1069
ERROR 2023-09-13 15:50:03,869 log 2612 8480 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 135, in form_valid
    self.object = form.save()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\forms\models.py", line 542, in save
    self.instance.save()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1833, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\backends\base\operations.py", line 213, in fetch_returned_insert_columns
    return cursor.fetchone()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\utils.py", line 97, in inner
    with self:
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
django.db.utils.OperationalError: database is locked
ERROR 2023-09-13 15:50:03,878 basehttp 2612 8480 "POST /hw_4/client/add/ HTTP/1.1" 500 153773
ERROR 2023-09-13 15:50:34,625 log 2612 8480 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'hw_4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py", line 17, in get_absolute_url
    return reverse('hw_4:client_page', kwargs={'pk': self.pk})
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'hw_4' is not a registered namespace
ERROR 2023-09-13 15:50:34,630 basehttp 2612 8480 "POST /hw_4/client/add/ HTTP/1.1" 500 114702
INFO 2023-09-13 15:50:50,728 basehttp 2612 8480 "GET /hw_4/client/add/ HTTP/1.1" 200 1069
ERROR 2023-09-13 15:50:57,689 log 2612 8480 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'hw_4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py", line 17, in get_absolute_url
    return reverse('hw_4:client_page', kwargs={'pk': self.pk})
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'hw_4' is not a registered namespace
ERROR 2023-09-13 15:50:57,692 basehttp 2612 8480 "POST /hw_4/client/add/ HTTP/1.1" 500 114702
INFO 2023-09-13 16:10:46,937 autoreload 2612 1384 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py changed, reloading.
INFO 2023-09-13 16:10:47,699 autoreload 10948 8456 Watching for file changes with StatReloader
INFO 2023-09-13 16:10:50,243 basehttp 10948 9836 "GET /hw_4/client/add/ HTTP/1.1" 200 1069
INFO 2023-09-13 16:39:15,917 autoreload 10948 8456 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\urls.py changed, reloading.
INFO 2023-09-13 16:39:16,595 autoreload 3096 10292 Watching for file changes with StatReloader
ERROR 2023-09-13 16:39:33,289 log 3096 15008 Internal Server Error: /hw_4/client/add/
Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'hw_4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py", line 17, in get_absolute_url
    return reverse('hw_4:client_page', kwargs={'pk': self.pk})
  File "C:\Users\TESO\Desktop\Lessions\Framework Django\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'hw_4' is not a registered namespace
ERROR 2023-09-13 16:39:33,293 basehttp 3096 15008 "POST /hw_4/client/add/ HTTP/1.1" 500 114767
INFO 2023-09-13 16:47:54,324 autoreload 3096 10292 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py changed, reloading.
INFO 2023-09-13 16:47:55,021 autoreload 1152 2176 Watching for file changes with StatReloader
INFO 2023-09-13 16:51:26,612 autoreload 1152 2176 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\models.py changed, reloading.
INFO 2023-09-13 16:51:27,743 autoreload 920 12164 Watching for file changes with StatReloader
INFO 2023-09-13 16:53:49,293 autoreload 920 12164 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\myproject\urls.py changed, reloading.
INFO 2023-09-13 16:53:50,228 autoreload 4628 18888 Watching for file changes with StatReloader
INFO 2023-09-13 16:56:54,325 autoreload 4628 18888 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\urls.py changed, reloading.
INFO 2023-09-13 16:56:55,460 autoreload 4636 920 Watching for file changes with StatReloader
INFO 2023-09-13 16:58:21,916 autoreload 4636 920 C:\Users\TESO\Desktop\Lessions\Framework Django\myproject\hw_4\views.py changed, reloading.
INFO 2023-09-13 16:58:23,037 autoreload 18352 5764 Watching for file changes with StatReloader
INFO 2023-09-13 16:59:57,935 autoreload 13284 17000 Watching for file changes with StatReloader
